import type { Metadata } from "next";
import "./ui/globals.css";
import { inter } from "./ui/font";
import NavBar from "./ui/navbar";


export const metadata: Metadata = {
  title: "Social Paroi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
